import imp
import time
import os
import random

# L code
print('=====114514年高科技=====')
time.sleep(1)
print('开始破解')
os.system('cls')
print('=--------- %10')
a = random.randrange(1,10,5)
time.sleep(a)
os.system('cls')
print('==-------- %20')
a = random.randrange(1,10,5)
time.sleep(a)
os.system('cls')
print('===------- %30')
a = random.randrange(1,10,5)
time.sleep(a)
os.system('cls')
print('====------ %40')
a = random.randrange(1,10,5)
time.sleep(a)
os.system('cls')
print('=====----- %50')
a = random.randrange(1,10,5)
time.sleep(a)
os.system('cls')
print('=======--- %70')
a = random.randrange(1,10,5)
time.sleep(a)
os.system('cls')
print('========== %99')
os.system('cls')
os.system('start https://player.bilibili.com/player.html?aid=80433022')
print('你被骗了 rick roll!')
os.system('pause')
